projects/__init__.py
from flask import Flask

def create_app(script_info=None):
    from projects.scraper.views import scraper_blueprint


    app = Flask(__name__, static_url_path='')

    # register blueprint
    app.register_blueprint(scraper_blueprint)

    return app

projects/scraper/views.py
import glob
import json
import os

from flask import jsonify, request, redirect, url_for, render_template
from flask.blueprints import Blueprint

from projects.scraper.scrapers.steam import get_detail, get_all_link, data_product

# blueprint config
scraper_blueprint = Blueprint('scraper', __name__, template_folder='templates', static_folder='static')


# route
@scraper_blueprint.route('/', methods=['GET', 'POST'])
def index():
    keywords = request.form.get('keywords')
    if request.method == 'POST':
        all_product = get_all_link(keywords=keywords)
        for product in all_product:
            products = get_detail(product)
            data_product.append(products)

        print("Total Data Product {}".format(len(data_product)))

        # writing json
        # write json
        results_dir = os.path.dirname(os.path.realpath(__file__))
        with open(f'{os.path.join(results_dir, "scrapers/results")}/{keywords.replace("+", " ")}.json', 'w+') as outfile:
            json.dump(data_product, outfile)

        return redirect('/api')
    else:
        return render_template('index.html')


# api
@scraper_blueprint.route('/api')
def api():
    datas = []
    json_dir = os.path.dirname(os.path.realpath(__file__))
    file_results = sorted(glob.glob(os.path.join(json_dir, 'scrapers/results/*.json')))
    for file in file_results:
        print('Reading File: {}'.format(file))
        with open(file, 'r') as json_file:
            json_data = json.load(json_file)
        datas += json_data
    return jsonify(games=datas)

projects/scraper/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bulma.min.css') }}">
    <title>
        {% block titles %} {% endblock titles %} -Steam Scraper
    </title>
</head>
<body>
{% block contents %}

{% endblock contents %}

</body>
</html>

projects/scraper/templates/index.html
{% extends "base.html" %}

{% block titles %}
Scraper
{% endblock %}


{% block contents %}
{% include "partials/navbar.html" %}
<div class="container is-fluid">
    <form action="" method="POST">
        <div class="field">
        <label class="label">Game Keywords</label>
          <div class="control">
            <input name="keywords" class="input" type="text" placeholder="Enter A Keyword: ">
              <br>
              <br>
              <button type="submit" class="button is-success">Generate Data</button>
          </div>
    </form>
  <p class="help">Ex: Among Us to Scraping Among Us Results</p>
</div>

</div>
{% endblock contents %}

projects/scraper/templates/partials/navbar.html
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="/">
      <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
    </a>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a href="/" class="navbar-item">Home</a>
      <a href="{{ url_for('scraper.api') }}" class="navbar-item">API</a>
      </div>
    </div>
  </div>
</nav>